apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cilium.io/global: "true"
  labels:
    app: httpbin
    role: server
  name: httpbin
  namespace: stateless-services
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: httpbin
    role: server
  type: ClusterIP
