apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curl
    role: client
  name: curl
  namespace: operations
spec:
  replicas: 2
  selector:
    matchLabels:
      app: curl
      role: client
  template:
    metadata:
      labels:
        app: curl
        role: client
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - curl
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - image: ghcr.io/ksdpmx/curl:6af1a00
        imagePullPolicy: IfNotPresent
        command:
        - tail
        - -f
        name: curl
      nodeSelector:
        deployment.group: worker
      serviceAccount: default
      serviceAccountName: default
